name = "gg"
version = "0.0.1"
description = "A Grammar of Graphics charting library for Gleam"
licenses = ["Apache-2.0"]
repository = { type = "github", user = "paaradiso", repo = "gg" }

target = "javascript"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
